### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by mattkram** [pyscript/pyscript-cli#12]

**Comment by Asmitha-K** [comment]
Hi
Is the contribution guidelines for pyscript-cli similar to contribution guidelines for pyscript ?
If yes, can I give it a try?

**Comment by mattkram** [comment]
Hi! Sorry, I didn't put many details. We will inherit what is appropriate from `pyscript`, but will have different instructions for dev setup. If you'd like to help contribute, I could use some help working through:

- setting up pre-commit locally
- installing locally with poetry
- running automated tests

In general, anything related to organization, governance, code of conduct, etc. should reference main PyScript repo.

**Comment by Asmitha-K** [comment]
Thank you so much for replying. 
I am not very sure about the instructions for dev setup but I can do the rest of the contribution guidelines. So I wanted to know if it is fine if I create a PR for this issue and do everything except the dev setup and later you can help me or assign someone for the dev setup part.
If it doesn't sound feasible, I can do something else that you suggest 😊

**Comment by FabioRosado** [comment]
Hello been doing some gardening on this issues 😄 
We not have a contributing guide we can now close this issue (even tho they probably need some love)
