### ISSUE TITLE
Add a plugin system

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript-cli#23]
Similar to [core PyScript](https://github.com/pyscript/pyscript/), the core team will focus mainly on the core functionality of the tool that should do few things that work. The number of custom features that the community may need are extremely high though (for instance, it's easy to think that the[ pyscript-collective](https://github.com/pyscript/pyscript-collective) may want to add custom cmds/features to the cli to better serve its needs that may not belong in the core feature set of `pyscript-cli`.

For this reason, I think it's important for us to start with a [simple yet] opinionated plugin system that can encourage the ecosystem and community growth around the CLI from the start.

Imho, this plugin system should create hooks that allow plugins to hook into specific parts/events of the workflow in order to extend the cli functionality. For example, adding new commands, new attributes for specific commands or the CLI in general.

**Comment by mattkram** [comment]
Love this idea. I have a feeling there must be some click-based frameworks for plugins we should explore. I love the idea of developing the CLI in a roughly similar way to pytest, which has an amazing plugin system and is distributed with several "standard" plugins by default.

**Comment by fpliger** [comment]
@mattkram Do you have any ideas/suggestions? 

Did a quick search and couldn't find anything solid for typer/click.... Been playing with a basic concept though

**Comment by mattkram** [comment]
This one looks promising: https://github.com/click-contrib/click-plugins

**Comment by fpliger** [comment]
Ah, had seen it but at that point thought it might be worth just using `pluggy` to hook into `entrypoints`.

The registration through setuptools entrypoints is not the most complicated part (it's just boilerplate), more about the design...

**Comment by mattkram** [comment]
I definitely haven't done any real work here. I'd lean towards `pluggy`, just since it's so popular and supported, but I haven't had any time to look into the details yet.

**Comment by mattkram** [comment]
Just one thought I'd like to add. There is a recent PEP that was passed so now setup.py isn't required, so we should ensure whatever solution we come up with allows more modern pyproject.toml packages too (I think it should work).
