### ISSUE TITLE
create cmd template should have external config and script 

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript-cli#47]
Currently, the `create` cmd generates `index.html` and `manifest.json` (soon to be `pyscript.toml` #46  ). But

1. the config is not loaded into `<py-config>` at all
2. the python script should be in an external file and not inline (in order for us to encourage best practices and more flexibility)

**Comment by FabioRosado** [comment]
I am closing this issue as it's out dated. The new template is not using main.py and pyscript.toml but the code in index.html is very old and needs updating.
