### ISSUE TITLE
create cmd should use the latest release PyScript version dynamically

### ISSUE THREAD

**Issue by fpliger** [pyscript/pyscript-cli#66]
As mentioned in #65, we currently manually pin the PyScript version to be used on a new PyScript app. Ideally, we should determine that dynamically but hitting an API and taking the latest value from there. 

This way, when I run `pyscript create`, the cmd can connect to this API, determine what's the latest release and use that to fill the new app html template

**Comment by madhur-tandon** [comment]
Is there an endpoint that I can hit so as to determine the latest release version?

I mean, the URL https://api.github.com/repos/pyscript/pyscript/releases/latest works, but only when we mark our releases as `latest`, which we do not currently, as all of them are marked as `pre-release`

<img width="632" alt="Screenshot 2023-07-12 at 2 07 33 AM" src="https://github.com/pyscript/pyscript-cli/assets/20173739/274828b7-863d-4612-91b2-19bca41a1290">

CC: @fpliger

**Comment by mchilvers** [comment]
Actually, we decided NOT to do this automatically, but to give each release of PyScript a few weeks to settle before we bump the CLI. I'm happy if we bite the bullet and go automatic... but don't really mind :)
